### ISSUE TITLE
A question about the benchmark results.

### ISSUE THREAD

**Issue by Little-Podi** [jimmy-dq/DropMAE#1]
Congrats for such a great work! May I ask why the AiATrack results in Table 2 of your arXiv verison are so low? I am happy to provide the raw results or any other kinds of help if you meet trouble in reproducing AiATrack. Thanks!

**Comment by Little-Podi** [comment]
Plus, it's not a big deal since it's not SOTA anymore, but I still hope to know so that I can fix the underlying bugs in the open-source work accordingly. Please kindly shoot me a message if you have time.

**Comment by Little-Podi** [comment]
FYI, the original results can be found [here](https://github.com/Little-Podi/AiATrack#bookmarkstrong-performance).

**Comment by jimmy-dq** [comment]
Hi Shenyuan, 
Thanks for your comments. I just checked the AIATrack results on LaSOT in Table 2, yes, it should be a typo. For LaSOT_ext, I use Table 3 in your paper w/ the variant of "AiA in both"  (46.8/54.4/54.2) for comparison , which is slightly different from the results reported in your git. What's the diff? 
Anyway, I will fix the typos in the arxiv version.

**Comment by Little-Podi** [comment]
I see, thanks for your quick reply and generous help. I totally understand for such a solid work this is just a minor issue. From Table 5 in AiATrack paper, you will find that I have done some parameter tuning to push the performance. Thus, the publicly released raw results on GitHub are under the best settings, i.e., LaSOT (69.0/79.4/73.8) & LaSOT_ext (47.7/55.6/55.4). You are free to verify my results via running the evaluation. I sincerely appreciate your help if you can update the results accordingly. BTW, you guys are so rich with an enviable amount of GPU resources, hahaha :)
