### ISSUE TITLE
Pretrained checkpoint

### ISSUE THREAD

**Issue by Huiimin5** [jimmy-dq/DropMAE#3]
Thank you so much for sharing the code of this work!

Do you mind releasing the pretrained ViT checkpoint? 

Many thanks!

**Comment by jimmy-dq** [comment]
Hi, currently we are preparing the codes, pre-trained and downstream fine-tuned models, which will be released in the next few days (within this week). Hope this can help your research and thanks for your interests.

**Comment by Huiimin5** [comment]
Glad to know that you will release them soon. 
Could you please also release ViT-B pretrained for 400 epochs on K400? Thank you so much for your consideration.
