### ISSUE TITLE
Finetune Codes

### ISSUE THREAD

**Issue by LingyiHongfd** [jimmy-dq/DropMAE#4]
Thank you so much for sharing the checkpoint and codes of pretraining. And do you mind releasing the finetune codes for vot and vos? Thanks a lot.

**Comment by YconfigY** [comment]
you can visit: https://github.com/jimmy-dq/DropTrack

**Comment by jimmy-dq** [comment]
> Thank you so much for sharing the checkpoint and codes of pretraining. And do you mind releasing the finetune codes for vot and vos? Thanks a lot.

@LingyiHongfd  The VOS fine-tuning is available at https://github.com/jimmy-dq/DropSeg.
