### ISSUE TITLE
Download of Kinetics Datasets

### ISSUE THREAD

**Issue by AmadeusSTQ** [jimmy-dq/DropMAE#9]
Dear Authors:
    Thanks for your great work!
    I have downloaded the Kinetics 700-2020 which is provided in this [link](https://www.deepmind.com/open-source/kinetics).
    However, i find there are just urls in *.json rather than video files after decompressing it.
    Could you provide some scripts to download videos files from the urls, splitting them according to *.csv?
    I am very grateful if you provide further instructions about Kinetics dataset!

**Comment by jimmy-dq** [comment]
> Dear Authors: Thanks for your great work! I have downloaded the Kinetics 700-2020 which is provided in this [link](https://www.deepmind.com/open-source/kinetics). However, i find there are just urls in *.json rather than video files after decompressing it. Could you provide some scripts to download videos files from the urls, splitting them according to *.csv? I am very grateful if you provide further instructions about Kinetics dataset!

Hi, the detailed instructions can be found here https://github.com/cvdfoundation/kinetics-dataset.
